RD-52113 [*] Migrate Terraform project to Gitlab
https://finalcad.atlassian.net/browse/RD-52113

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -16,9 +16,9 @@ inputs:
   terragrunt-version:
     description: 'Terragrunt version to install.'
     default: '0.68.1'
-  terraform-app-lambda:
-    description: 'terraform app lambda repository'
-    default: 'FinalCAD/terraform-app-lambda'
+  terraform-app-lambda-git-url:
+    description:  'Git url to use for pulling repo terraform-app-lambda'
+    default: 'git@gitlab.com:orisha-group/construction/advae/common/infrastructure/terraform-app-lambda.git'
   terraform-app-lambda-ref:
     description: 'Ref to use for pulling repo terraform-app-lambda'
     default: 'master'
@@ -67,15 +67,63 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - uses: actions/checkout@v7
+    - name: Setup SSH agent
+      uses: webfactory/ssh-agent@v0.10.0
+      with:
+        ssh-private-key: ${{ inputs.github-ssh }}
+    - name: Setup SSH known hosts
+      shell: bash
+      run: |
+        echo '::group::Setup SSH known hosts'
+        [[ -d ~/.ssh ]] || mkdir -p ~/.ssh
+        ssh-keyscan github.com >> ~/.ssh/known_hosts
+        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
+        echo '::endgroup::'
+    - name: Checkout application repository
+      uses: actions/checkout@v7
       with:
         path: 'lambda'
-    - uses: actions/checkout@v7
+    - name: Checkout terragrunt repository
+      shell: bash
+      run: |
+        echo '::group::Checkout terragrunt repository'
+        git clone \
+          --progress \
+          --branch '${{ inputs.terraform-app-lambda-ref }}' \
+          --depth 1 \
+          --no-tags \
+          '${{ inputs.terraform-app-lambda-git-url }}' \
+          'terragrunt'
+        echo '::endgroup::'
+    - name: Copy application files
+      shell: bash
+      run: |
+        set -e
+        application_file='./lambda/${{ inputs.configuration-file }}'
+        if ! [ -f "${application_file}" ]; then
+          echo "application file '${application_file}' is missing"
+          exit 1
+        fi
+        cp "${application_file}" ./terragrunt/lambda.yaml
+
+        policy_file='./lambda/${{ inputs.policies-file }}'
+        if [ -f "${policy_file}" ]; then
+          cp "${policy_file}" ./terragrunt/lambda-policies.json
+        fi
+    - name: Setup go
+      uses: actions/setup-go@v7
       with:
-        ssh-key: ${{ inputs.github-ssh }}
-        repository: ${{ inputs.terraform-app-lambda }}
-        ref: ${{ inputs.terraform-app-lambda-ref }}
-        path: 'terragrunt'
+        token: ${{ inputs.github-token }}
+        go-version: 1.18
+    - name: Setup cue
+      shell: bash
+      run: |
+        go install cuelang.org/go/cmd/cue@v0.4.3
+    - name: Cue vetting
+      shell: bash
+      run: |
+        set -e
+        cue vet ./terragrunt/application.yaml ./terragrunt/application.cue
     - name: Checkout deployment descriptor repository
       uses: actions/checkout@v7
       with:
@@ -100,17 +148,6 @@ runs:
         esac
         echo "awsregion=${awsregion}" >> $GITHUB_OUTPUT
         echo "region=${region}" >> $GITHUB_OUTPUT
-    # Setup ssh key
-    - name: Add ssh key
-      shell: bash
-      run: |
-        set -e
-        mkdir -p ~/.ssh
-        echo "${{ inputs.github-ssh }}" > ~/.ssh/id_rsa
-        ssh-keyscan github.com >> ~/.ssh/known_hosts
-        chmod 600 ~/.ssh/id_rsa ~/.ssh/known_hosts
-        eval $(ssh-agent)
-        ssh-add ~/.ssh/id_rsa
     - name: Detect Python archive
       id: python_archive
       shell: bash
@@ -122,7 +159,7 @@ runs:
         fi
     - name: Set up Python
       if: steps.python_archive.outputs.python_archive == 'true'
-      uses: actions/setup-python@v6
+      uses: actions/setup-python@v7
       with:
         python-version: ${{ inputs.python-version }}
     - name: Add custom layer
@@ -178,11 +215,6 @@ runs:
     - name: Terragrunt plan
       shell: bash
       run: |
-        cp ./lambda/${{ inputs.configuration-file }} ./terragrunt/lambda.yaml || exit $?
-
-        if [ -f ./lambda/${{ inputs.policies-file }} ]; then
-          cp ./lambda/${{ inputs.policies-file }} ./terragrunt/lambda-policies.json || exit $?
-        fi
         cd ./terragrunt/${{ inputs.environment }}/${{ inputs.region-friendly }}/lambda &&
         export TF_VAR_application_id=${{ inputs.app-name }} &&
         export TF_VAR_application_suffix=${{ inputs.suffix }} &&
